AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "Gemfile"
    - 'tmp/**/*'
    - 'log/**/*'
    - 'test/**/*'

Style/StringLiterals:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
